### PR TITLE
update states title fonts after rebrand.

### PR DESCRIPTION
**Pull request by lw354**

### CODE REVIEW

**Comment by groves** [comment]
Could you include in the message when you merge this where these fonts came from and what the change is?

**Comment by lw354** [comment]
They are the Titling Gothic FB fonts from the [ST Brand Library](https://drive.google.com/drive/folders/1yy5SkMC8IEn19H_i9tpesn9yWP4peS6Q).

**Comment by groves** [comment]
ahh, I was just hoping to get that in the commit that got merged in

**Comment by lw354** [comment]
Boo, that was a -m fail on the merge. I can force push an amended message, it's not great practice but this is a very small repo?

**Pull request merged**
